// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FSharp.AWS.DynamoDB")>]
[<assembly: AssemblyProductAttribute("FSharp.AWS.DynamoDB")>]
[<assembly: AssemblyDescriptionAttribute("An F# wrapper over the standard Amazon.DynamoDB library")>]
[<assembly: AssemblyVersionAttribute("0.12.4")>]
[<assembly: AssemblyFileVersionAttribute("0.12.4")>]
[<assembly: InternalsVisibleToAttribute("FSharp.AWS.DynamoDB.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.AWS.DynamoDB"
    let [<Literal>] AssemblyProduct = "FSharp.AWS.DynamoDB"
    let [<Literal>] AssemblyDescription = "An F# wrapper over the standard Amazon.DynamoDB library"
    let [<Literal>] AssemblyVersion = "0.12.4"
    let [<Literal>] AssemblyFileVersion = "0.12.4"
    let [<Literal>] InternalsVisibleTo = "FSharp.AWS.DynamoDB.Tests"
